import streamlit as st
from PIL import Image

from api import vision

from components.header import load_css
from components.sidebar import sidebar

from components.vision_ui import (
    image_preview,
    ai_dashboard,
    findings,
    conditions,
    recommendations
)

# ==========================================================
# PAGE CONFIG
# ==========================================================

st.set_page_config(
    page_title="Medical Vision AI",
    page_icon="🩺",
    layout="wide",
    initial_sidebar_state="expanded"
)

load_css()
sidebar()

# ==========================================================
# SESSION STATE
# ==========================================================

if "vision_result" not in st.session_state:
    st.session_state.vision_result = None

# ==========================================================
# HERO
# ==========================================================

st.markdown("""
<div class="hero">

<h1>🖼️ Medical Vision AI</h1>

<p>
Upload skin disease images, X-rays, MRI scans,
CT scans or other medical images and receive
an AI-powered clinical analysis.
</p>

</div>
""", unsafe_allow_html=True)

# ==========================================================
# FILE UPLOAD
# ==========================================================

uploaded_image = st.file_uploader(
    "📂 Drag & Drop Medical Image",
    type=["jpg", "jpeg", "png"],
    help="Supported formats: JPG, JPEG, PNG"
)

# ==========================================================
# IMAGE PREVIEW
# ==========================================================

if uploaded_image is not None:

    image = Image.open(uploaded_image)

    st.success(f"✅ Uploaded: {uploaded_image.name}")

    left, right = st.columns([1.2, 1])

    with left:

        st.markdown("## 📷 Uploaded Image")

        image_preview(image)

    with right:

        st.markdown("## 🤖 AI Dashboard")

        st.info("""
Supported Image Types

• Skin Diseases

• X-Ray

• MRI

• CT Scan

• Clinical Images
""")

    st.divider()

    if st.button(
        "🧠 Analyze Medical Image",
        use_container_width=True
    ):

        with st.spinner("🩺 AI is analyzing the medical image..."):

            try:

                st.session_state.vision_result = vision(uploaded_image)

            except Exception as e:

                st.error(f"Error: {e}")

# ==========================================================
# SHOW RESULT
# ==========================================================

if st.session_state.vision_result is not None:

    result = st.session_state.vision_result

    confidence = result.get("confidence", 0)

    severity = result.get("severity", "Unknown")

    st.success("✅ Analysis Completed Successfully")

    st.progress(confidence / 100)

    st.divider()

    left, right = st.columns([1, 2])

    with left:

        ai_dashboard(result)

        st.markdown("### 📊 AI Statistics")

        st.metric("Confidence", f"{confidence}%")

        st.metric("AI Engine", "Gemini 2.5")

        st.metric("Knowledge Base", "Medical Vision AI")

        st.metric(
            "Image Type",
            result.get("image_type", "Unknown")
        )

        st.markdown("### 🚨 Severity")

        sev = severity.lower()

        if sev == "low":

            st.success("🟢 LOW")

        elif sev == "medium":

            st.warning("🟡 MEDIUM")

        elif sev == "high":

            st.error("🟠 HIGH")

        else:

            st.error("🔴 CRITICAL")

    with right:

        findings(
            result.get(
                "findings",
                "No findings available."
            )
        )

    st.divider()

    st.markdown("## 🦠 Possible Conditions")

    conditions(
        result.get(
            "possible_conditions",
            []
        )
    )

    st.divider()

    st.markdown("## 💡 Recommendations")

    recommendations(
        result.get(
            "recommendations",
            []
        )
    )

    st.divider()

    st.markdown("## 📈 Analysis Summary")

    c1, c2, c3 = st.columns(3)

    with c1:
        st.metric("Scan Status", "Completed")

    with c2:
        st.metric("Processing", "< 3 sec")

    with c3:
        st.metric("Model", "Vision AI")

    st.divider()

    st.info(
        result.get(
            "disclaimer",
            "This analysis is generated by AI and should not replace professional medical advice."
        )
    )

# ==========================================================
# CLEAR RESULT
# ==========================================================

st.sidebar.divider()

if st.sidebar.button(
    "🗑 Clear Analysis",
    use_container_width=True
):

    st.session_state.vision_result = None

    st.rerun()